### ISSUE TITLE
Flatpak / Snap package

### ISSUE THREAD

**Issue by Mikaela** [FiloSottile/captive-browser#17]
Flatpak and Snap attempt to be the universal Linux package managers and I think supporting either of them would make Captive Browser easier to install and upgrade.

* [ ] Flatpak
    * http://docs.flatpak.org/en/latest/first-build.html & https://github.com/flathub/flathub/wiki/App-Submission
* [ ] Snap
    * https://snapcraft.io/first-snap#go

**Comment by FiloSottile** [comment]
I'm happy for captive-browser to be packaged for any and all systems, but I do not appreciate the snap model of shifting the burden of packaging to the upstream. There are simply too many systems for the upstream to take care of packaging for them all.
