### ISSUE TITLE
How do you install and use this in Linux Ubuntu 18.04 bionic?

### ISSUE THREAD

**Issue by phd21** [FiloSottile/captive-browser#18]
Hi FiloSottile (Captive browser),

Thanks for providing this. It looks interesting. But, I cannot get this to run and I do have Chrome installed? I think I have the correct Go packages installed, can you be specific as to which Linux GO packages? 

I downloaded this twice first using the "git clone" and another time with the archive file. But, I cannot see how to install this or run it. I have read the GitHub and the readme and tried various console terminal commands, but nothing happens? Typing in "captive-browser" does nothing except command not found.

I am using Linux KDE Neon user edition and Linux Mint 19.x Cinnamon both are based on Ubuntu 18.04. I have only tried KDE neon with this so far.

Regards,
Phil (phd21)

**Comment by FiloSottile** [comment]
You need to use `go get` to install the tool, select a config file according to the README instructions, and then you can run it from `~/go/bin/captive-browser` by default. I realize this is not very user-friendly, but I did not have the time to automate more of the installation.

**Comment by phd21** [comment]
Hi FiloSottile,

Thank you for your reply.
This is what happens when I try the "go get"
`go get -u github.com/FiloSottile/captive-browser`
# github.com/FiloSottile/captive-browser
go/src/github.com/FiloSottile/captive-browser/main.go:93:9: dialer.Control undefined (type *net.Dialer has no field or method Control)

This is what I get trying to run it after I ran the Ubuntu command.
`cp $(go env GOPATH)/src/github.com/FiloSottile/captive-browser/captive-browser-ubuntu-chrome.toml ~/.config/captive-browser.toml`

`~/go/bin/captive-browser`
bash: /home/user69/go/bin/captive-browser: No such file or directory

Regards,
Phil (phd21)

**Comment by FiloSottile** [comment]
Your version of Go is too old, this tool requires at least Go 1.11.

**Comment by phd21** [comment]
Hi FiloSottile,

Thank you for your reply.

I am using "golang" v1.10 from Ubuntu 18.04 bionic (KDE Neon and Linux Mint 19.x) which is fairly new. Any way to reduce the requirement from Golang v1.11 to v1.10 so this would work on those systems?

Regards,
Phil (phd21)

**Comment by phd21** [comment]
Hi FiloSottile,

`go version`
go version go1.12.2 linux/amd64

`go get -u github.com/FiloSottile/captive-browser`
go get github.com/FiloSottile/captive-browser: open /usr/local/go/bin/captive-browser: permission denied

 `sudo go get -u github.com/FiloSottile/captive-browser`
 github.com/FiloSottile/captive-browser
go/src/github.com/FiloSottile/captive-browser/main.go:93:9: dialer.Control undefined (type *net.Dialer has no field or method Control)

Regards,
Phil (phd21)
