### ISSUE TITLE
DHCP DNS server detection via DBus/systemd-resolved

### ISSUE THREAD

**Issue by chrissnell** [FiloSottile/captive-browser#7]
Hi Filippo,

I have written some code to query DBus to determine the nameserver that was provided by DHCP to `systemd-networkd`, which is commonly used on Arch Linux systems and probably many others.  I like this method because it makes it easier for the user running this stack.  No complicated shell commands, just provide an interface name like `eth0` and the code does the rest.   

I'd like to work this into a PR for **captive-browser** but I'd like to know if you're interested in it.  Also, how would the user provide the interface name?  An entry in the TOML config file perhaps?  Maybe something like this:

```
systemd-networkd-dhcp-interface = "eth0"
```
Let me know and I'll put something together.

**Comment by FiloSottile** [comment]
Closed by #8
